# -*- coding: utf-8 -*-
"""python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmSFYHtf6X8sqhLJW-V2Fykz0nevbRCs
"""

# Simple Python Code

print("Hello, I am learning Google Colab!")

name = input("Enter your name: ")
print("Welcome", name)

# Simple calculation
a = 10
b = 5
print("Sum =", a + b)
print("Multiplication =", a * b)